# Generated by Django 4.2.2 on 2023-10-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_insctructure_rename_discount_course_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insctructure',
            name='email',
        ),
        migrations.RemoveField(
            model_name='insctructure',
            name='name',
        ),
    ]
