# Generated by Django 4.2.2 on 2023-10-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_insctructure_email_remove_insctructure_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rating',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Insctructure',
        ),
        migrations.AddField(
            model_name='course',
            name='author_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Insctructure',
        ),
    ]
