# Generated by Django 4.2.2 on 2023-10-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_rating_course_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insctructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='discount',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='Insctructure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.insctructure'),
            preserve_default=False,
        ),
    ]
